[build]
  command = "yarn deploy"
  publish = "packages/webamp/demo/built"

# A short URL for listeners of https://changelog.com/podcast/291
[[redirects]]
  from = "/changelog"
  to = "/#%7B\"initialTracks\"%3A%5B%7B\"url\"%3A\"https%3A%2F%2Fcdn.changelog.com%2Fuploads%2Fpodcast%2F291%2Fthe-changelog-291.mp3\"%2C\"metaData\"%3A%7B\"artist\"%3A\"Changelog%20Podcast\"%2C\"title\"%3A\"Winamp2-js\"%7D%7D%5D%7D"

[[redirects]]
  from = "/about"
  to = "https://github.com/captbaritone/webamp"

# Redirect domain aliases to primary domain
[[redirects]]
  from = "https://webamp.net/*"
  to = "https://webamp.org/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "10"